version: 0.1

environment_variables:
  plaintext:
    BUILD_TARGET_SITE=test-documentation.conversations.actionable.co

phases:
  install:
    commands:
      - gem update --system
      - gem install jekyll
  build:
    commands:
      - bundle update
      - bundle exec jekyll build
      - "aws s3 sync _site/ s3://$BUILD_TARGET_SITE"